# Generated by Django 3.1.6 on 2021-03-25 12:25

from django.db import migrations, models
import django.db.models.deletion
import regex


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'enquiries'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=15, validators=[regex.validate_phone]),
        ),
        migrations.CreateModel(
            name='EnquiryEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_email', to='enquiry.enquiry')),
            ],
        ),
    ]
